### ISSUE TITLE
Auto Jump To Cursor Issues with daily notes

### ISSUE THREAD

**Issue by SpencerTackett** [SilentVoid13/Templater#1112]
Hi there,

I have a daily note template that looks like this:

`---
Aliases: <% tp.date.now("YYYY-MM-DD") %>
---
[[ <% tp.date.now("YYYY-MM-DD - ddd MMM D", -1, tp.file.title, "YYYY-MM-DD - ddd MMM D") %>|Yesterday]] | [[<% tp.date.now("YYYY-MM-DD - ddd MMM D", 1, tp.file.title, "YYYY-MM-DD - ddd MMM D") %>|Tomorrow]]

<% tp.file.cursor() %>`

I have "automatic jump to cursor" enabled as well as "trigger templater on new file creation."

When I trigger this template manually everything works as expected. However, when the note is created automatically via calendar plugin or "open today's daily note" in the command palette, the note is created, the cursor jumps to the correct place, but then the text "<% tp.file.cursor() %>" is re-inserted to the file. Does anyone know what would be causing this?

**Comment by EvanEdwards** [comment]
I am seeing this occur intermittently with version 1.16.0 (current as of my writing this).  It didn't occur until I modified my template recently, although since it is intermittent, I can not say what edit triggered the bug.

**Comment by Zachatoo** [comment]
I use `tp.file.cursor()` in my daily notes and I haven't experience this issue. I would appreciate if someone can narrow down what is causing this issue or confirm that this has been fixed.

**Comment by EvanEdwards** [comment]
As a bit of information:  I have not seen the issue recently.  It is plausible it has been resolved, or was due to a conflict with some other Plugin that I no longer use (I wish there was an option to clear all but one plugin for testing purposes for this reason).

**Comment by davidolrik** [comment]
I still have this issue, as described here: https://github.com/SilentVoid13/Templater/issues/1232#issuecomment-1822347301

**Comment by joyous-coder** [comment]
> As a bit of information: I have not seen the issue recently. It is plausible it has been resolved, or was due to a conflict with some other Plugin that I no longer use (I wish there was an option to clear all but one plugin for testing purposes for this reason).

I disable all my extensions but templater, the issue still exists.

**Comment by Zachatoo** [comment]
@joyous-coder Is it the same issue as described in #1232 where you're in reading mode, and therefore there is nowhere to put your cursor?

**Comment by Zachatoo** [comment]
Closing due to no response.
