### ISSUE TITLE
IT just stopped working today

### ISSUE THREAD

**Issue by timothyjlaurent** [SilentVoid13/Templater#24]
**Plugin informations (please complete the following information):**
 - OS: OSX Catalina
 - Templater version: 0.4.4
 - Obsidian version:  0.9.21
 - Templater settings: 
![image](https://user-images.githubusercontent.com/2000204/101439809-37769680-38ca-11eb-8bcf-e35c7b88ed32.png)

(My template dir gets blown away each time I upgrade btw)
**Describe the bug**
I try to add a template I have that looks like this:

```markdown
---
tags: #daily-log
---
<<[[{{tp_yesterday}}]]::[[{{tp_tomorrow}}]]

tags:#daily-log

# {{tp_today}}

```

which would always work but now nothing happens
**Expected behavior**
I should get a templated note

**Screenshots**
![image](https://user-images.githubusercontent.com/2000204/101439998-a7851c80-38ca-11eb-8f38-5c1e6b0e724d.png)
![image](https://user-images.githubusercontent.com/2000204/101440021-b4a20b80-38ca-11eb-96cb-644409203db9.png)

**Comment by SilentVoid13** [comment]
Hey @timothyjlaurent, i'm aware of the issue, this has been fixed in #21.
Just pushed the new release implementing the fix now :+1:

**Comment by timothyjlaurent** [comment]
Awesome, I updated, but it wasn't fixed until I restarted Obsidian. Thanks for the fix and the sweet plugin!!
