### ISSUE TITLE
Error generating daily quote

### ISSUE THREAD

**Issue by koldex** [SilentVoid13/Templater#800]
**Plugin information (please complete the following information):**

-   OS: Mac OS X 12.5.1
-   Templater version: 1.13.0
-   Obsidian version: 0.16.2

**Describe the bug**
Templater cannot generate a daily quote. 

**Expected behavior**
Daily quote to be generated normally when template is applied.

**Screenshots**
plugin:templater-obsidian:2734          GET https://api.quotable.io/random net::ERR_NAME_NOT_RESOLVED

**Additional context**
[obsidian.md-1662354906060.log](https://github.com/SilentVoid13/Templater/files/9486857/obsidian.md-1662354906060.log)

**Comment by welpdx** [comment]
This seems to be an issue with your dns. Try flushing dns and see if that fixes this issue:
1. [tenforum](https://www.tenforums.com/tutorials/69623-flush-dns-resolver-cache-windows-10-a.html#:~:text=in%20Google%20Chrome-,Flush%20DNS%20Resolver%20Cache%20for%20Windows%2010%20in%20Command%20Prompt,command%20prompt%20if%20you%20like.)
2. [appuals](https://appuals.com/how-to-fix-error-err_name_not_resolved-on-google-chrome/)

**Comment by koldex** [comment]
Not that. I've both disabled by pi-hole dns resolver as well as flushed/restarted it and the issue remains.
![quatable io query](https://user-images.githubusercontent.com/89720922/188383836-605329e9-8f36-49b7-8671-b3a5183cba0e.png)

**Comment by shabegom** [comment]
Would happily merge a pull request with an alternative daily quote api

**Comment by aziham** [comment]
> This seems to be an issue with your dns. Try [flushing dns](https://wpbeaches.com/flush-dns-cache-locally-in-macos-big-sur-catalina-osx-linux-and-windows/) and see if that fixes this issue. something like `sudo killall -HUP mDNSResponder` or something.
> 
> Edit: mac os not windows

`api.quotable.io` is down, see: https://github.com/lukePeavey/quotable/issues

I think that templater should use multiple quotes providers to avoid this problem in the future.

Example: try provider 1 if no response move to the next provider and so on. If all providers are down then we can return an error message.

**Comment by koldex** [comment]
> > This seems to be an issue with your dns. Try [flushing dns](https://wpbeaches.com/flush-dns-cache-locally-in-macos-big-sur-catalina-osx-linux-and-windows/) and see if that fixes this issue. something like `sudo killall -HUP mDNSResponder` or something.
> > Edit: mac os not windows
> 
> `api.quotable.io` is down, see: https://github.com/lukePeavey/quotable/issues
> 
> I think that templater should use multiple quotes providers to avoid this problem in the future.
> 
> Example: try provider 1 if no response move to the next provider and so on. If all providers are down then we can return an error message.

The exception handling works just fine today (unlike in the past when the parsing stopped to this error). Now you get a string "Error generating daily quote" as a result if this 'tp.web.daily_quote' fails it's job.

**Comment by welpdx** [comment]
Weird. Cause I tried to rep your issue last night with just <% tp.web.daily_quote() %> and I got no errors or anything

**Comment by koldex** [comment]
> Weird. Cause I tried to rep your issue last night with just <% tp.web.daily_quote() %> and I got no errors or anything

Perhaps api.quotable.io was not down during that time. Now it seems to be up as well so the templater works as well.

**Comment by shabegom** [comment]
If you have other APIs we could try please share them.

**Comment by koldex** [comment]
> If you have other APIs we could try please share them.

There are plenty of them out there, e.g.

1. https://rapidapi.com/collection/quote-generator-apis
2. https://zenquotes.io
3. https://theysaidso.com/api/#curl

**Comment by welpdx** [comment]
> > Weird. Cause I tried to rep your issue last night with just <% tp.web.daily_quote() %> and I got no errors or anything
> 
> Perhaps api.quotable.io was not down during that time. Now it seems to be up as well so the templater works as well.

I tested it the minute this post was made. Perhaps the api was down but idk. I have seen other bug reports here though.
Perhaps we can use an alternative if default api returns error

**Comment by welpdx** [comment]
Also, it is kinda weird that you got an error. Didn't we enclose that in a try catch? @shabegom

**Comment by aziham** [comment]
> > > This seems to be an issue with your dns. Try [flushing dns](https://wpbeaches.com/flush-dns-cache-locally-in-macos-big-sur-catalina-osx-linux-and-windows/) and see if that fixes this issue. something like `sudo killall -HUP mDNSResponder` or something.
> > > Edit: mac os not windows
> > 
> > 
> > `api.quotable.io` is down, see: https://github.com/lukePeavey/quotable/issues
> > I think that templater should use multiple quotes providers to avoid this problem in the future.
> > Example: try provider 1 if no response move to the next provider and so on. If all providers are down then we can return an error message.
> 
> The exception handling works just fine today (unlike in the past when the parsing stopped to this error). Now you get a string "Error generating daily quote" as a result if this 'tp.web.daily_quote' fails to do it's job.

Yes, I've noticed that in the latest update a try catch block was added. But my suggestion is about adding multiple quotes providers so if one is doww, Templater's daily quote will continue to work.

**Comment by aziham** [comment]
https://github.com/lukePeavey/quotable/issues/142

The issue was fixed, the API is up.

![](https://user-images.githubusercontent.com/8286271/188540328-e968a1c0-eaa6-4181-896d-a5fe1282e742.png)

**Comment by shabegom** [comment]
> Also, it is kinda weird that you got an error. Didn't we enclose that in a try catch? @shabegom 

@welpdx It will still throw an error if it hits the `catch` block. The try/catch just prevents the rest of the templater processing from stopping so people don't have broken daily notes.
