### ISSUE TITLE
1.15 syntax highlighting is causing live preview to fail

### ISSUE THREAD

**Issue by Lulullia** [SilentVoid13/Templater#893]
**Plugin information (please complete the following information):**

-   OS: Windows 10
-   Templater version: 1.15.1 & 1.15
-   Obsidian version: 1.0.3
-   Templater settings: these had no problems before

**Describe the bug**
Just updated, and Obsidian's editor is broken. It only shows Source view (or rather, it shows what Notepad might show, aka plain unformatted markdown), now way to trigger Live Preview. I tried with the command "Toggle Live Preview", with the little icon button in the status bar.

EDIT: The issue is also present in 1.15, everything goes back to normal after reverting to the last 1.14

**Expected behavior**
Templater shouldn't mess with the editor.

**Screenshots**
Templater 1.15.1 enabled:
![image](https://user-images.githubusercontent.com/47358820/198852456-e087e7bb-ab5e-4b92-8a89-21f2e64a9237.png)

Templater disabled (with no other actions taken since the last screenshot):
![image](https://user-images.githubusercontent.com/47358820/198852440-8deac4c1-7c98-4670-91b0-f057c02fff95.png)

For reference, this is what Source view looks like under normal circumstances:
![image](https://user-images.githubusercontent.com/47358820/198852675-85605a5e-b57c-40df-85bc-c82e7d8ca763.png)

**Comment by rodrigo-rufino** [comment]
Same for me!

**Comment by ultraflynn** [comment]
I’m seeing this also. Just updated Templater and still seeing weird behaviour.

**Comment by shabegom** [comment]
Thanks for reporting.

1.15.1 should fix this for mobile apps
1.15.2 should fix this for desktop apps if syntax highlighting is disabled in the settings.

Please let me know if this continues to be an issue after updating to 1.15.2

**Comment by Lulullia** [comment]
@shabegom Thanks for the quick fix! 1.15.2 works normally.

Since there's still a problem with syntax highlighting, the issue should be kept open, right?

**Comment by shabegom** [comment]
Closing since it seems the issue with live preview is resolved. Will eventually get around to the problem of highlighting not working on mobile.
